name: Build and Deploy Documentation

on:
  push:
    branches:
      - main  # Trigger on changes to the main branch

jobs:
  # Checkout code
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install dependencies
    - name: Install dependencies
      run: |
        pip install sphinx
        pip install breathe  
        pip install sphinx_rtd_theme

    # Build documentation in Sphinx
    - name: Build documentation
      run: 
        sphinx-build -b html docs/source docs/build/html
    
    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
        publish_branch: gh-pages
